# The URL the site will be built for
base_url = "http://lukefrisken.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Theme name to use
theme = "zulma"

# Whether to generate a RSS feed automatically
generate_rss = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = false},
    {name = "authors", rss = false},
]

[extra]
zulma_menu = [
    {url = "$BASE_URL/adventures", name = "Adventures"},
    {url = "$BASE_URL/code", name = "Code"},
    {url = "$BASE_URL/tags/maps", name = "Maps"},
    {url = "$BASE_URL/photos", name = "Photos"},
    {url = "$BASE_URL/about/contact", name = "Contact"},
]

images_enabled = true

zulma_brand = {text = "Home"}
zulma_title = "Luke Frisken"

disqus_sitename = "lukefrisken"

# url to use for map tile layer https://leafletjs.com/reference-1.6.0.html#tilelayer
map_tile_url = "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png"

# attribution html
map_tile_attribution = "Kartendaten: © <a href=\"https://openstreetmap.org/copyright\">OpenStreetMap</a>-Mitwirkende, SRTM | Kartendarstellung: © <a href=\"http://opentopomap.org\">OpenTopoMap</a> (<a href=\"https://creativecommons.org/licenses/by-sa/3.0/\">CC-BY-SA</a>)"

# whether or not to show the fullscreen button for maps
map_fullscreen_button = true

# whether or not to show the home button for maps
map_home_button = false