# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

taxonomies = [
    {name = "categories"},
    {name = "tags", paginate_by = 5, rss = true},
    {name = "authors", rss = true},
]

build_search_index = true

[extra]
zulma_themes = ["default", "darkly", "flatly", "pulse", "simplex", "lux", "slate", "solar", "superhero"]

zulma_menu = [
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/authors", name = "Authors"}
]
zulma_brand = {text = "Home"}
zulma_title = "My Blog"
zulma_theme = "darkly"
zulma_allow_theme_selection = true

images_enabled = false

# url to use for map tile layer https://leafletjs.com/reference-1.6.0.html#tilelayer
map_tile_url = "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png"

# attribution html
map_tile_attribution = "Kartendaten: © <a href=\"https://openstreetmap.org/copyright\">OpenStreetMap</a>-Mitwirkende, SRTM | Kartendarstellung: © <a href=\"http://opentopomap.org\">OpenTopoMap</a> (<a href=\"https://creativecommons.org/licenses/by-sa/3.0/\">CC-BY-SA</a>)"

# whether or not to show the fullscreen button for maps
map_fullscreen_button = true

# whether or not to show the home button for maps
map_home_button = false